name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install
        working-directory: frontend  # Set working directory to your React app folder

      - name: Build React app
        run: npm run build
        working-directory: frontend

      - name: Zip artifact for deployment
        run: zip -r release.zip frontend/build  # Zip only the build folder

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'calc1-app-webapp'
          slot-name: 'Production'
          package: frontend/build  # Deploy only the build folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2110489858134C80BE3BE96D90CA8BFC }}

